### ISSUE TITLE
Add the code to move the robot backwards and forwards on the beam

### ISSUE THREAD

**Issue by jkmosa01** [Shazbots1245/BEST2018#4]
Buttons 5U and 6U unless anyone objects

**Comment by jkmosa01** [comment]
I want one of the new programmers (@bob8898 or @malder08) to do this. Would like to get this done by end of meeting on Tuesday September 4th. (Hopefully we have a functioning robot by then too)

**Comment by bob8898** [comment]
We were thinking to use the l/r triggers to move... single dimension movement doesn't require a joystick.

**Comment by jkmosa01** [comment]
We're using buttons Buttons 5U and 6U. See diagrams.
