### ISSUE TITLE
Control the swivel of the gripper

### ISSUE THREAD

**Issue by jkmosa01** [Shazbots1245/BEST2018#5]
What buttons should we use?

**Comment by bob8898** [comment]
I could take care of this part... We were thinking of using the 2 joysticks to control the arm.

**Comment by jkmosa01** [comment]
I think we need to have a (potentially long) discussion about what which buttons we want to use.

**Comment by jkmosa01** [comment]
If we do end up doing a 2 joint arm we need to be able to maneuver it quickly and have it be intuitive.

**Comment by bob8898** [comment]
We drew it out to have 4DOF...

**Comment by jkmosa01** [comment]
So we have one swivel, a rotation on top of the swivel that is connected to the PVC pipe with another rotation there, and then the scooper at the end with probably another rotation there.

**Comment by bob8898** [comment]
Yeah... That would be fairly difficult to control with just buttons... Joysticks seem more intuitive, but youre right... We need to discuss how to control the arm... For reference, how do we get the raw values from the joysticks? I'm a bit unfamiliar with the vex cortex and how it interacts with the controller in the code. I do understand the buttons though.

**Comment by bob8898** [comment]
The joysticks also provide forward/reverse control on 4 axes...

**Comment by jkmosa01** [comment]
I'm thinking the joysticks to control the swivel and 2 arm rotations, and then the other triggers (not used for movement on beam) to tilt the scooper.
`vexRT[Ch3]` will return the vertical position of the left joystick on a scale of -100 to 100 (I think)
Then just use those as the speed at which the motor is moving.
For servos it will work differently because they take positional values (from -128 to 128) so we would have to create a variable and then add or subtract from it (shouldn't be hard though)

**Comment by jkmosa01** [comment]
Again, don't get to hung up on programming, we can probably code the robot in under 30 minutes. We are going to need more help with mechanical and design.

**Comment by bob8898** [comment]
So the joystick labels are tied to Channels... So for left horizontal, its Ch4 The scooper makes sense to only have buttons... Not much stuff needed there. For the servos, we can use the map function... That doesn't exist in raw c, but i can put it in really easy. 
 `long map(long x, long in_min, long in_max, long out_min, long out_max)
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}`
I also am just trying to get myself familiar with the controller. You're definitely right about mechanical / design being much more difficult... We cant do much about that currently until next meeting.

**Comment by jkmosa01** [comment]
It would be much easier to just make a variable and control it with that (just add or subtract 1)...

**Comment by bob8898** [comment]
True... We'll cross that bridge when we come to it.

**Comment by jkmosa01** [comment]
Ok. We also have a picture of the controller with a map of all of the buttons [here](https://github.com/Shazbots1245/BEST2018/blob/master/VEXX%20Controller%20with%20Labels.jpg) You'll have to donwload it, but it's fully labeled with all of the buttons and channels of joysticks

**Comment by jkmosa01** [comment]
Need to wait for the Mechanical team to finish this (probably after kickoff). Can have them start working this week (week of 9/10)
