### ISSUE TITLE
Add labeled pinout of MCU

### ISSUE THREAD

**Issue by bob8898** [Shazbots1245/BEST2018#6]
We need to add a pinout of the vex core so we can assign outputs.

**Comment by jkmosa01** [comment]
???

**Comment by jkmosa01** [comment]
Are we talking about where we plug the motors in to the cortex?

**Comment by bob8898** [comment]
Yes.

**Comment by jkmosa01** [comment]
Ok. I don't think its necessary since we just plug in the motor to a number we choose and then that number corresponds to the port number in the code.

**Comment by bob8898** [comment]
Yup...
